/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package rentalkendaraan;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JTable;


/**
 *
 * @author 
 */
public class AplikasiRentalKendaraan extends javax.swing.JFrame {
int A=0;


    public AplikasiRentalKendaraan() {
        initComponents();
tombolPanelKendaraan.setVisible(false);
tombolMember.setVisible(false);
kosong.setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kendaraan = new javax.swing.JButton();
        member = new javax.swing.JButton();
        penyewaan = new javax.swing.JButton();
        pengembalian = new javax.swing.JButton();
        datapenyewaan = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane()
        ;
        jLabel2 = new javax.swing.JLabel();
        tombolPanelKendaraan = new javax.swing.JPanel();
        tambahkendaraan = new javax.swing.JButton();
        editkendaraan = new javax.swing.JButton();
        tombolMember = new javax.swing.JPanel();
        tambahmember = new javax.swing.JButton();
        editmember = new javax.swing.JButton();
        kosong = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 102, 255)));

        kendaraan.setText("Data Kendaraan");
        kendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kendaraanActionPerformed(evt);
            }
        });
        kendaraan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kendaraanKeyPressed(evt);
            }
        });
        jPanel1.add(kendaraan);

        member.setText("Data Member");
        member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberActionPerformed(evt);
            }
        });
        jPanel1.add(member);

        penyewaan.setText("Penyewaan");
        penyewaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penyewaanActionPerformed(evt);
            }
        });
        jPanel1.add(penyewaan);

        pengembalian.setText("Form Pengembalian");
        pengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengembalianActionPerformed(evt);
            }
        });
        jPanel1.add(pengembalian);

        datapenyewaan.setText("Data Penyewaan");
        datapenyewaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datapenyewaanActionPerformed(evt);
            }
        });
        jPanel1.add(datapenyewaan);

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jPanel1.add(keluar);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Kelompok GG ");

        tombolPanelKendaraan.setBackground(new java.awt.Color(0, 255, 0));
        tombolPanelKendaraan.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 0)));

        tambahkendaraan.setText("TAMBAH");
        tambahkendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahkendaraanActionPerformed(evt);
            }
        });
        tombolPanelKendaraan.add(tambahkendaraan);

        editkendaraan.setText("EDIT");
        editkendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editkendaraanActionPerformed(evt);
            }
        });
        tombolPanelKendaraan.add(editkendaraan);

        tombolMember.setBackground(new java.awt.Color(51, 255, 51));
        tombolMember.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 255, 0)));
        tombolMember.setForeground(new java.awt.Color(51, 255, 0));

        tambahmember.setText("TAMBAH");
        tambahmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahmemberActionPerformed(evt);
            }
        });
        tombolMember.add(tambahmember);

        editmember.setText("EDIT");
        editmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editmemberActionPerformed(evt);
            }
        });
        tombolMember.add(editmember);

        jLabel3.setBackground(new java.awt.Color(0, 255, 255));
        jLabel3.setFont(new java.awt.Font("High Tower Text", 3, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Sistem Database Rental Mobil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(tombolPanelKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(319, 319, 319)
                        .addComponent(kosong, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, Short.MAX_VALUE)
                        .addComponent(tombolMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(303, 303, 303))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kosong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tombolPanelKendaraan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tombolMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void pengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengembalianActionPerformed
Kembali kembali = new Kembali();
kembali.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_pengembalianActionPerformed

    private void kendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kendaraanActionPerformed
        tampilTabel();
        tombolPanelKendaraan.setVisible(true);
tombolMember.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_kendaraanActionPerformed

    private void kendaraanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kendaraanKeyPressed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_kendaraanKeyPressed

    private void memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberActionPerformed
         tampilTabel2();
        tombolMember.setVisible(true);
tombolPanelKendaraan.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_memberActionPerformed

    private void penyewaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penyewaanActionPerformed
Sewa sewa = new Sewa();
sewa.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_penyewaanActionPerformed

    private void tambahkendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahkendaraanActionPerformed
TambahKendaraan tambah = new TambahKendaraan();
tambah.setVisible(true);
dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_tambahkendaraanActionPerformed

    private void editkendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editkendaraanActionPerformed
EditKendaraan tambah = new EditKendaraan();
tambah.setVisible(true);
dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_editkendaraanActionPerformed

    private void tambahmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahmemberActionPerformed
TambahMember tambah = new TambahMember();
tambah.setVisible(true);
dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahmemberActionPerformed

    private void editmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editmemberActionPerformed
EditMember tambah = new EditMember();
tambah.setVisible(true);
dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_editmemberActionPerformed

    private void datapenyewaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datapenyewaanActionPerformed
tampilTabel3();
tombolPanelKendaraan.setVisible(false);
tombolMember.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_datapenyewaanActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_keluarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiRentalKendaraan().setVisible(true);
                new TambahKendaraan().setVisible(false);
            }
        });
    }
    
private Object[][] getData(){

        String user="root";
        String pswd ="";
        String host="localhost";
        String db="rentalkendaraan";
        String url="";

        Object[][] data1= null;

        try {
            Class.forName("com.mysql.jdbc.Driver");

            url="jdbc:mysql://"+ host +"/"+ db + "?user=" + user + "&password="+ pswd;
            Connection conn=DriverManager.getConnection(url);

            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM datakedaraan ORDER BY kodekend");

            rs.last();
            int rowCount= rs.getRow();
            rs.beforeFirst();

            data1= new Object[rowCount][11];
            int no=-1;
            while (rs.next()) {
                no=no+1;
                data1[no][0]=rs.getString("kodekend");
                data1[no][1]=rs.getString("jenis");
                data1[no][2]=rs.getString("kategori");
                data1[no][3]=rs.getString("biayasewaenamjam");
                data1[no][4]=rs.getString("biayasewaduabelasjam");
                data1[no][5]=rs.getString("biayasewaduaempatjam");
                data1[no][6]=rs.getString("biayasewaempatdelapanjam");
                data1[no][7]=rs.getString("overtime");
                data1[no][8]=rs.getString("jumlah");

            }

          st.close();
          conn.close();

       }

       catch(ClassNotFoundException e) {
            System.out.println("jdbc.Driver tidak ditemukan");
       }

       catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
       }
        return data1;
    }
public void tampilTabel() {
        String[] columnNames = {"KODE","JENIS KENDARAAN","NAMA MOBIL", "BIAYA 6 JAM",
         "BIAYA 12 JAM","BIAYA 24 JAM"
                ,"BIAYA 48 JAM","OVERTIME","JUMLAH"};
        JTable table = new JTable(getData(), columnNames);
        jScrollPane1.setViewportView(table);
tombolPanelKendaraan.setVisible(true);
}
 private Object[][] getData2(){

        String user="root";
        String pswd ="";
        String host="localhost";
        String db="rentalkendaraan";
        String url="";

        Object[][] data1= null;

        try {
            Class.forName("com.mysql.jdbc.Driver");

            url="jdbc:mysql://"+ host +"/"+ db + "?user=" + user + "&password="+ pswd;
            Connection conn=DriverManager.getConnection(url);

            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM datamember ORDER BY kode");

            rs.last();
            int rowCount= rs.getRow();
            rs.beforeFirst();

            data1= new Object[rowCount][11];
            int no=-1;
            while (rs.next()) {
                no=no+1;
                data1[no][0]=rs.getString("kode");
                data1[no][1]=rs.getString("nama");
                data1[no][2]=rs.getString("alamat");
                data1[no][3]=rs.getString("telepon");
            }

          st.close();
          conn.close();

       }

       catch(ClassNotFoundException e) {
            System.out.println("jdbc.Driver tidak ditemukan");
       }

       catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
       }
        return data1;
    }
public void tampilTabel2() {
        String[] columnNames = {"KODE","NAMA","ALAMAT", "TELEPON"};
        JTable table2 = new JTable(getData2(), columnNames);
        jScrollPane1.setViewportView(table2);
tombolMember.setVisible(true);
}
private Object[][] getData3(){

        String user="root";
        String pswd ="";
        String host="localhost";
        String db="rentalkendaraan";
        String url="";

        Object[][] data1= null;

        try {
            Class.forName("com.mysql.jdbc.Driver");

            url="jdbc:mysql://"+ host +"/"+ db + "?user=" + user + "&password="+ pswd;
            Connection conn=(Connection) DriverManager.getConnection(url);

            Statement st = (Statement) conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM datasewa ORDER BY kode");

            rs.last();
            int rowCount= rs.getRow();
            rs.beforeFirst();

            data1= new Object[rowCount][10];
            int no=-1;
            while (rs.next()) {
                no=no+1;
                data1[no][0]=rs.getString("kode");
                data1[no][1]=rs.getString("nama");
                data1[no][2]=rs.getString("kodekend");
                data1[no][3]=rs.getString("kategori");
                data1[no][4]=rs.getString("biaya");
                data1[no][5]=rs.getString("waktusewa");
                data1[no][6]=rs.getString("overtime");
                data1[no][7]=rs.getString("jumlahovertime");
                data1[no][8]=rs.getString("biayaovertime");


            }

          st.close();
          conn.close();

       }

       catch(ClassNotFoundException e) {
            System.out.println("jdbc.Driver tidak ditemukan");
       }

       catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
       }
        return data1;
    }
public void tampilTabel3() {
        String[] columnNames = {"KODE","NAMA","KODE KENDARAAN","NAMA MOBIL", "BIAYA",
        "WAKTU SEWA", "OVERTIME","JUMLAH OVERTIME"
                ,"BIAYA OVERTIME"};
        JTable tabel = new JTable(getData3(), columnNames);
        jScrollPane1.setViewportView(tabel);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton datapenyewaan;
    private javax.swing.JButton editkendaraan;
    private javax.swing.JButton editmember;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluar;
    private javax.swing.JButton kendaraan;
    private javax.swing.JPanel kosong;
    private javax.swing.JButton member;
    private javax.swing.JButton pengembalian;
    private javax.swing.JButton penyewaan;
    private javax.swing.JButton tambahkendaraan;
    private javax.swing.JButton tambahmember;
    private javax.swing.JPanel tombolMember;
    private javax.swing.JPanel tombolPanelKendaraan;
    // End of variables declaration//GEN-END:variables
 

}
