/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


package rentalkendaraan;

import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author 
 */
public class EditKendaraan extends javax.swing.JFrame {
    public Connection conn;
    public Statement cn;
        String user="root";
        String pswd ="";
        String host="localhost";
        String db="rentalkendaraan";
        String url="";
        private Connection Lconnection=null;


    public EditKendaraan() {
        initComponents();
                simpan.setEnabled(false);
        try {

            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://"+ host +"/"+ db + "?user=" + user + "&password="+ pswd;

            Lconnection=DriverManager.getConnection(url);
        }

        catch(ClassNotFoundException e) {
            System.out.println("Driver tidak ditemukan");
        }

        catch (SQLException e){
            System.out.println("koneksi gagal:" +
                 e.toString());
        }

    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jenis = new javax.swing.JTextField();
        overtime = new javax.swing.JTextField();
        cekkode = new javax.swing.JButton();
        kode = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        kategori = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        enamjam = new javax.swing.JTextField();
        duabelasjam = new javax.swing.JTextField();
        duapuluhempatjam = new javax.swing.JTextField();
        empatpuluhdelapanjam = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        simpan = new javax.swing.JButton();
        menuutama = new javax.swing.JButton();
        tabelkendaraan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cekkode.setText("CEK KODE");
        cekkode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekkodeActionPerformed(evt);
            }
        });

        kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeActionPerformed(evt);
            }
        });

        jLabel2.setText("JENIS");

        jLabel1.setText("KODE");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 1, true), "BIAYA SEWA"));

        jLabel8.setText("6 JAM");

        jLabel9.setText("12 JAM");

        jLabel10.setText("24 JAM");

        jLabel11.setText("48 JAM");

        duapuluhempatjam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                duapuluhempatjamKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                duapuluhempatjamKeyTyped(evt);
            }
        });

        empatpuluhdelapanjam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                empatpuluhdelapanjamKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enamjam, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(duabelasjam, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(duapuluhempatjam, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(empatpuluhdelapanjam, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(enamjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(duabelasjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(duapuluhempatjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empatpuluhdelapanjam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(34, 34, 34))
        );

        jLabel5.setText("OVERTIME");

        jLabel4.setText("JUMLAH");

        jLabel3.setText("NAMA MOBIL");

        simpan.setText("SIMPAN");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        menuutama.setText("KEMBALI");
        menuutama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuutamaActionPerformed(evt);
            }
        });

        tabelkendaraan.setText("Data Kendaraan");
        tabelkendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabelkendaraanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(cekkode))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabelkendaraan)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(kode, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                        .addComponent(jenis)
                        .addComponent(kategori)
                        .addComponent(jumlah)
                        .addComponent(overtime)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(menuutama)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(overtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cekkode)
                    .addComponent(simpan)
                    .addComponent(menuutama)
                    .addComponent(tabelkendaraan))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cekkodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekkodeActionPerformed
 try {
            Statement st = (Statement) Lconnection.createStatement();
            ResultSet rs = st.executeQuery("Select * from datakedaraan" +
                    " where kodekend='" + kode.getText() + "'");
            if (rs.next()) {
                simpan.setEnabled(true);
                cekkode.setEnabled(true);
                kode.setText(rs.getString("kodekend"));
                jenis.setText(rs.getString("jenis"));
                kategori.setText(rs.getString("kategori"));
                enamjam.setText(rs.getString("biayasewaenamjam"));
                duabelasjam.setText(rs.getString("biayasewaduabelasjam"));
                duapuluhempatjam.setText(rs.getString("biayasewaduaempatjam"));
                empatpuluhdelapanjam.setText(rs.getString("biayasewaempatdelapanjam"));
                overtime.setText(rs.getString("overtime"));
                jumlah.setText(rs.getString("jumlah"));

            } else {
                JOptionPane.showMessageDialog(this,"Kode: Salah", "Informasi",
                        JOptionPane.INFORMATION_MESSAGE);

                simpan.setEnabled(false);
            kode.setText("");
            jenis.setText("");
            kategori.setText("");
            enamjam.setText("");
            duabelasjam.setText("");
            duapuluhempatjam.setText("");
            empatpuluhdelapanjam.setText("");
            overtime.setText("");
            jumlah.setText("");
                            kode.requestFocus();
            }
        } catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());

        }
         // TODO add your handling code here:
}//GEN-LAST:event_cekkodeActionPerformed

    private void duapuluhempatjamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_duapuluhempatjamKeyReleased

        // TODO add your handling code here:
}//GEN-LAST:event_duapuluhempatjamKeyReleased

    private void duapuluhempatjamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_duapuluhempatjamKeyTyped


        // TODO add your handling code here:
}//GEN-LAST:event_duapuluhempatjamKeyTyped

    private void empatpuluhdelapanjamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empatpuluhdelapanjamKeyReleased

        // TODO add your handling code here:
}//GEN-LAST:event_empatpuluhdelapanjamKeyReleased

    public void koneksi(){
 
try{
 
Class.forName("com.mysql.jdbc.Driver");
 
conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/rentalkendaraan","root","");
 
cn = conn.createStatement();
 
}catch (Exception e){
 
JOptionPane.showMessageDialog(this,"koneksi gagal..",
 
"Error",JOptionPane.ERROR_MESSAGE);
 
System.out.println(e.getMessage());
 
}
 
}
    
    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
 try{
 
koneksi();
 
String sql = "update datakedaraan set kodekend='"+ kode.getText() +"',"+" jenis='" + jenis.getText() + "'"
        + ","+" kategori ='" +kategori.getText() +"'"
        + ","+" jumlah ='" +jumlah.getText() +"'"
        + ","+" overtime ='" +overtime.getText() +"'"
        + ","+" biayasewaenamjam ='" +enamjam.getText() +"'"
        + ","+" biayasewaduabelasjam ='" +duabelasjam.getText() +"'"
        + ","+" biayasewaduaempatjam ='" +duapuluhempatjam.getText() +"'"
        + ","+" biayasewaempatdelapanjam ='" +empatpuluhdelapanjam.getText() +"'"
        + "" +"where kodekend='" + kode.getText() + "'";
 
cn.executeUpdate(sql);

 
JOptionPane.showMessageDialog(null,"Data berhasil di rubah");
 
}catch (Exception e){
 
JOptionPane.showMessageDialog(null,"Proses update gagal/koneksi gagal..");
 
System.out.println(e.getMessage());
 
}

        // TODO add your handling code here:
    }//GEN-LAST:event_simpanActionPerformed

    private void menuutamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuutamaActionPerformed
        AplikasiRentalKendaraan tambah2 = new AplikasiRentalKendaraan();
        tambah2.setVisible(true);
        dispose();
        tambah2.tampilTabel();
        // TODO add your handling code here:
    }//GEN-LAST:event_menuutamaActionPerformed

    private void tabelkendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabelkendaraanActionPerformed
        // TODO add your handling code here:
        ShowKendaraan show = new ShowKendaraan();
        show.setVisible(true);
    }//GEN-LAST:event_tabelkendaraanActionPerformed

    private void kodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodeActionPerformed


    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditKendaraan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cekkode;
    private javax.swing.JTextField duabelasjam;
    private javax.swing.JTextField duapuluhempatjam;
    private javax.swing.JTextField empatpuluhdelapanjam;
    private javax.swing.JTextField enamjam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jenis;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField kategori;
    private javax.swing.JTextField kode;
    private javax.swing.JButton menuutama;
    private javax.swing.JTextField overtime;
    private javax.swing.JButton simpan;
    private javax.swing.JButton tabelkendaraan;
    // End of variables declaration//GEN-END:variables

}