/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package rentalkendaraan;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 
 */
public class Sewa extends javax.swing.JFrame {
  int subTotal;

    DefaultTableModel modelTable;
    String user="root";
        String pswd ="";
        String host="localhost";
        String db="rentalkendaraan";
        String url="";
        private Connection Lconnection=null;

    public Sewa() {
        initComponents();
        lamaovertime.setEnabled(false);
        masukkan.setEnabled(true);
        modelTable = (DefaultTableModel) tabel.getModel();
        overtime2.setVisible(false);
        try {

            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://"+ host +"/"+ db + "?user=" + user + "&password="+ pswd;

            Lconnection=DriverManager.getConnection(url);
        }

        catch(ClassNotFoundException e) {
            System.out.println("Driver tidak ditemukan");
        }

        catch (SQLException e){
            System.out.println("koneksi gagal:" +
                 e.toString());
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        kode = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kode2 = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();
        overtime2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        kode3 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        carimember = new javax.swing.JButton();
        waktusewa = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        lamaovertime = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        masukkan = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        tabelmember = new javax.swing.JButton();
        showkendaraan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("KODE MEMBER");

        kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("KODE");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("NAMA");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("ALAMAT");

        kode2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kode2.setText("...................................");

        nama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nama.setText(".......................");

        alamat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        alamat.setText(".......................");

        overtime2.setText(".");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)))
                .addGap(273, 273, 273)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(nama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alamat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kode2, 0, 1, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(overtime2)
                .addContainerGap(328, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kode2)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(alamat)
                    .addComponent(overtime2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("KODE KENDARAAN");

        kode3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kode3ActionPerformed(evt);
            }
        });

        tabel.setBackground(new java.awt.Color(102, 255, 255));
        tabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "KODE", "JENIS", "BIAYA", "OVERTIME", "LAMA OVERTIME", "BIAYA OVERTIME"
            }
        ));
        jScrollPane2.setViewportView(tabel);

        carimember.setText("CARI");
        carimember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carimemberActionPerformed(evt);
            }
        });

        waktusewa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "  ", "6 jam", "12 jam", "24 jam", "48 jam" }));
        waktusewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waktusewaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("PILIH WAKTU SEWA");

        jButton1.setText("KEMBALI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("LAMA OVERTIME ");

        lamaovertime.setText("00");
        lamaovertime.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                lamaovertimeComponentAdded(evt);
            }
        });
        lamaovertime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lamaovertimeMouseEntered(evt);
            }
        });
        lamaovertime.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lamaovertimeInputMethodTextChanged(evt);
            }
        });
        lamaovertime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lamaovertimeActionPerformed(evt);
            }
        });
        lamaovertime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lamaovertimeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lamaovertimeKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("JAM");

        masukkan.setText("MASUKKAN KE TABEL");
        masukkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masukkanActionPerformed(evt);
            }
        });

        simpan.setText("SIMPAN KE DATA SEWA");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        tabelmember.setText("DATA MEMBER");
        tabelmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabelmemberActionPerformed(evt);
            }
        });

        showkendaraan.setText("DATA KENDARAAN");
        showkendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showkendaraanActionPerformed(evt);
            }
        });

        jLabel5.setText("TOTAL");

        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(212, 212, 212)
                        .addComponent(kode, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(carimember)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tabelmember))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(169, 169, 169)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(waktusewa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lamaovertime)
                            .addComponent(kode3, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addGap(54, 54, 54)
                                .addComponent(masukkan))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel12))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(showkendaraan)))))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                                .addGap(106, 106, 106))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addComponent(simpan)
                                        .addGap(33, 33, 33)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(carimember)
                    .addComponent(kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tabelmember))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(kode3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showkendaraan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(waktusewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lamaovertime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(masukkan)
                    .addComponent(jLabel11))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpan)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carimemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carimemberActionPerformed
        try {
            Statement st = (Statement) Lconnection.createStatement();
            ResultSet rs = st.executeQuery("Select * from datamember" +
                    " where kode='" + kode.getText() + "'");
            if (rs.next()) {


                kode.setText(rs.getString("kode"));
                kode2.setText(rs.getString("kode"));
                nama.setText(rs.getString("nama"));
                alamat.setText(rs.getString("alamat"));


            } else {
                ShowMember show = new ShowMember();
                show.setVisible(true);
                //dispose();
            }
        } catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_carimemberActionPerformed

    private void kodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodeActionPerformed

    private void waktusewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waktusewaActionPerformed
        String a = null;
        int g = 0;
        int h = 0;
        try {
            Statement st = (Statement) Lconnection.createStatement();
            ResultSet rs = st.executeQuery("Select * from datakedaraan" +
                    " where kodekend='" + kode3.getText() + "'");
            if (rs.next()) {
            String c = rs.getString("biayasewaenamjam");
            String d = rs.getString("biayasewaduabelasjam");
            String e = rs.getString("biayasewaduaempatjam");
            String f = rs.getString("biayasewaempatdelapanjam");

if (waktusewa.getSelectedItem().equals("6 jam")){
a = c;
subTotal += Integer.parseInt(a);
    total.setText(""+subTotal);
    g = Integer.parseInt(rs.getString("overtime"))*h;
 }else if (waktusewa.getSelectedItem().equals("12 jam")){
a = d;
subTotal += Integer.parseInt(a);
    total.setText(""+subTotal);
    g = Integer.parseInt(rs.getString("overtime"))*h;
 }else if (waktusewa.getSelectedItem().equals("24 jam")){
a = e ;
subTotal += Integer.parseInt(a);
    total.setText(""+subTotal);
    g = Integer.parseInt(rs.getString("overtime"))*h;
}else if (waktusewa.getSelectedItem().equals("48 jam")){
a = f ;
   subTotal += Integer.parseInt(a);
    total.setText(""+subTotal);
    g = Integer.parseInt(rs.getString("overtime"))*h;
}
                modelTable.insertRow(modelTable.getRowCount(),
        new Object[]{rs.getString("kodekend"),rs.getString("jenis"),  a ,rs.getString("overtime"),h , g });
           } else {
                //ShowMember show = new ShowMember();
                //show.setVisible(true);
            }
        } catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());

        }

        if (waktusewa.getSelectedItem().equals("48 jam")){
    lamaovertime.setEnabled(true);
    tabel.setVisible(false);
    masukkan.setEnabled(true);
modelTable.setRowCount(0);
     subTotal = Integer.parseInt(a)-Integer.parseInt(a);
    total.setText(""+subTotal);
        }else {
             lamaovertime.setEnabled(true);
masukkan.setEnabled(true);
        }
       
        
        // TODO add your handling code here:
    }//GEN-LAST:event_waktusewaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lamaovertimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lamaovertimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lamaovertimeActionPerformed

    private void lamaovertimeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lamaovertimeKeyReleased
    // TODO add your handling code here:
    }//GEN-LAST:event_lamaovertimeKeyReleased

    private void lamaovertimeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lamaovertimeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_lamaovertimeKeyTyped

    private void lamaovertimeComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_lamaovertimeComponentAdded

        // TODO add your handling code here:
    }//GEN-LAST:event_lamaovertimeComponentAdded

    private void lamaovertimeInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lamaovertimeInputMethodTextChanged

        // TODO add your handling code here:
    }//GEN-LAST:event_lamaovertimeInputMethodTextChanged

    private void lamaovertimeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lamaovertimeMouseEntered

        // TODO add your handling code here:
    }//GEN-LAST:event_lamaovertimeMouseEntered

    private void masukkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukkanActionPerformed
        tabel.setVisible(true);
        String a = null;
        int g = 0;
        int h = 0;
        int j;
        try {
            Statement st = (Statement) Lconnection.createStatement();
            ResultSet rs = st.executeQuery("Select * from datakedaraan" +
                    " where kodekend='" + kode3.getText() + "'");
            if (rs.next()) {
            String c = rs.getString("biayasewaenamjam");
            String d = rs.getString("biayasewaduabelasjam");
            String e = rs.getString("biayasewaduaempatjam");
            String f = rs.getString("biayasewaempatdelapanjam");

    if (waktusewa.getSelectedItem().equals("6 jam")){
a = c;
subTotal += Integer.parseInt(a);
    total.setText(""+subTotal);
    j = subTotal + g;
   total.setText(""+j);
    overtime2.setText(""+6);
 }else if (waktusewa.getSelectedItem().equals("12 jam")){
a = d;
subTotal += Integer.parseInt(a);
    total.setText(""+subTotal);
    j = subTotal + g;
   total.setText(""+j);
overtime2.setText(""+12);
 }else if (waktusewa.getSelectedItem().equals("24 jam")){
a = e ;
subTotal += Integer.parseInt(a);
    total.setText(""+subTotal);
    j = subTotal + g;
   total.setText(""+j);
 overtime2.setText(""+24);
}else if (waktusewa.getSelectedItem().equals("48 jam")){
a = f  ;
int totalsemua = 0;
   subTotal += Integer.parseInt(a);
   j = subTotal + g;
   total.setText(""+j);
 overtime2.setText(""+48);
}
     g = Integer.parseInt(rs.getString("overtime"))*Integer.parseInt(lamaovertime.getText());
            h = Integer.parseInt(lamaovertime.getText());
                modelTable.insertRow(modelTable.getRowCount(),
        new Object[]{rs.getString("kodekend"),rs.getString("kategori"),  a ,rs.getString("overtime"),h , g });
           } else {
                ShowMember show = new ShowMember();
                show.setVisible(true);
            }
        } catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_masukkanActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        String user="root";
        String pswd ="";
        String host="localhost";
        String db="rentalkendaraan";
        String url="";
        int j;

        try {
            Class.forName("com.mysql.jdbc.Driver");

            url="jdbc:mysql://"+ host +"/"+ db + "?user=" + user + "&password="+ pswd;
            Connection conn=DriverManager.getConnection(url);

            PreparedStatement pStatement = conn.prepareStatement
                    ("INSERT INTO datasewa(kode,nama,kodekend,jenis,biaya,waktusewa,overtime,"
                    + "jumlahovertime,biayaovertime)" + "VALUES (?,?,?,?,?,?,?,?,?)");
            Statement st = (Statement) Lconnection.createStatement();
            ResultSet rs = st.executeQuery("Select * from datakedaraan" +
                    " where kodekend='" + kode3.getText() + "'");
        String a = null;
        int g = 0;
        int h = 0;


            if (rs.next()) {
            String c = rs.getString("biayasewaenamjam");
            String d = rs.getString("biayasewaduabelasjam");
            String e = rs.getString("biayasewaduaempatjam");
            String f = rs.getString("biayasewaempatdelapanjam");
g = Integer.parseInt(rs.getString("overtime"))*Integer.parseInt(lamaovertime.getText());
 if (waktusewa.getSelectedItem().equals("6 jam")){
a = c;
subTotal += Integer.parseInt(a);
j = subTotal+g;
    total.setText(""+j);

 }else if (waktusewa.getSelectedItem().equals("12 jam")){
a = d ;
subTotal += Integer.parseInt(a);
j = subTotal+g;
    total.setText(""+j);

 }else if (waktusewa.getSelectedItem().equals("24 jam")){
a = e ;
subTotal += Integer.parseInt(a);
    j = subTotal+g;
    total.setText(""+j);

}else if (waktusewa.getSelectedItem().equals("48 jam")){
a = f ;
   subTotal += Integer.parseInt(a);
   j = subTotal+g;
   total.setText(""+j);

}
g = Integer.parseInt(rs.getString("overtime"))*Integer.parseInt(lamaovertime.getText());
            pStatement.setString(1, kode.getText());
            pStatement.setString(2, nama.getText());
            pStatement.setString(3, kode3.getText());
            pStatement.setString(4, rs.getString("jenis"));
            pStatement.setString(5, a);
            pStatement.setString(6, (String) waktusewa.getSelectedItem());
            pStatement.setString(7, rs.getString("overtime"));
            pStatement.setString(8, lamaovertime.getText());
            pStatement.setString(9, Integer.toString(g));


            if (pStatement.executeUpdate()>0)
                JOptionPane.showMessageDialog(this,
                        "PENYIMPANAN SUKSES", "Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
            else
                JOptionPane.showMessageDialog(this,
                        "Penyimpanan gagal", "Informasi",
                        JOptionPane.INFORMATION_MESSAGE);

            pStatement.close();
            conn.close();

            kode.setText("");
            nama.setText("");
            alamat.setText("");
            kode3.setText("");
            lamaovertime.setText("");
            overtime2.setText("");
            waktusewa.getSelectedItem().equals("");
            total.setText("");
            modelTable.setRowCount(0);
            }
        }
        catch(ClassNotFoundException e) {
            System.out.println("jdbc.Driver tidak ditemukan");
        }

        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_simpanActionPerformed

    private void kode3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kode3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kode3ActionPerformed

    private void tabelmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabelmemberActionPerformed
        // TODO add your handling code here:
        ShowMember show = new ShowMember();
        show.setVisible(true);
    }//GEN-LAST:event_tabelmemberActionPerformed

    private void showkendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showkendaraanActionPerformed
        // TODO add your handling code here:
        ShowKendaraan show = new ShowKendaraan();
        show.setVisible(true);
    }//GEN-LAST:event_showkendaraanActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sewa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamat;
    private javax.swing.JButton carimember;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField kode;
    private javax.swing.JLabel kode2;
    private javax.swing.JTextField kode3;
    private javax.swing.JTextField lamaovertime;
    private javax.swing.JButton masukkan;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel overtime2;
    private javax.swing.JButton showkendaraan;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabel;
    private javax.swing.JButton tabelmember;
    private javax.swing.JTextField total;
    private javax.swing.JComboBox waktusewa;
    // End of variables declaration//GEN-END:variables

}
