package rentalkendaraan;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author 
 */
public class TambahKendaraan extends javax.swing.JFrame {

    public TambahKendaraan() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        enamjam = new javax.swing.JTextField();
        duabelasjam = new javax.swing.JTextField();
        duapuluhempatjam = new javax.swing.JTextField();
        empatpuluhdelapanjam = new javax.swing.JTextField();
        kode = new javax.swing.JTextField();
        jenis = new javax.swing.JTextField();
        kategori = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        overtime = new javax.swing.JTextField();
        simpan = new javax.swing.JButton();
        menuutama = new javax.swing.JButton();
        showkendaraan = new javax.swing.JButton();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("KODE");

        jLabel2.setText("JENIS");

        jLabel3.setText("NAMA MOBIL");

        jLabel4.setText("JUMLAH");

        jLabel5.setText("OVERTIME");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 1, true), "BIAYA SEWA"));

        jLabel8.setText("6 JAM");

        jLabel9.setText("12 JAM");

        jLabel10.setText("24 JAM");

        jLabel11.setText("48 JAM");

        duapuluhempatjam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                duapuluhempatjamKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                duapuluhempatjamKeyTyped(evt);
            }
        });

        empatpuluhdelapanjam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                empatpuluhdelapanjamKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enamjam, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(duabelasjam, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(duapuluhempatjam, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(empatpuluhdelapanjam, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(enamjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(duabelasjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(duapuluhempatjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empatpuluhdelapanjam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(40, 40, 40))
        );

        simpan.setText("SIMPAN");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        menuutama.setText("KEMBALI KE MENU UTAMA");
        menuutama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuutamaActionPerformed(evt);
            }
        });

        showkendaraan.setText("DATA KENDARAAN");
        showkendaraan.setActionCommand("DATA KENDARAAN");
        showkendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showkendaraanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kode, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(jenis)
                            .addComponent(kategori)
                            .addComponent(jumlah)
                            .addComponent(overtime)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(simpan)
                        .addGap(45, 45, 45)
                        .addComponent(showkendaraan)))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuutama)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(overtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpan)
                    .addComponent(menuutama)
                    .addComponent(showkendaraan))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empatpuluhdelapanjamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empatpuluhdelapanjamKeyReleased
 
        // TODO add your handling code here:
    }//GEN-LAST:event_empatpuluhdelapanjamKeyReleased

    private void duapuluhempatjamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_duapuluhempatjamKeyReleased
 
        // TODO add your handling code here:
    }//GEN-LAST:event_duapuluhempatjamKeyReleased

    private void duapuluhempatjamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_duapuluhempatjamKeyTyped
    // TODO add your handling code here:
    }//GEN-LAST:event_duapuluhempatjamKeyTyped

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        String user="root";
        String pswd ="";
        String host="localhost";
        String db="rentalkendaraan";
        String url="";

        try {
            Class.forName("com.mysql.jdbc.Driver");

            url="jdbc:mysql://"+ host +"/"+ db + "?user=" + user + "&password="+ pswd;
            Connection conn=DriverManager.getConnection(url);

            PreparedStatement pStatement = conn.prepareStatement
                    ("INSERT INTO datakedaraan(kodekend,jenis,kategori,biayasewaenamjam,biayasewaduabelasjam,"
                    + "biayasewaduaempatjam,biayasewaempatdelapanjam,overtime,jumlah)" + "VALUES (?,?,?,?,?,?,?,?,?)");

            pStatement.setString(1, kode.getText());
            pStatement.setString(2, jenis.getText());
            pStatement.setString(3, kategori.getText());
            pStatement.setString(4, enamjam.getText());
            pStatement.setString(5, duabelasjam.getText());
            pStatement.setString(6, duapuluhempatjam.getText());
            pStatement.setString(7, empatpuluhdelapanjam.getText());
            pStatement.setString(8, overtime.getText());
            pStatement.setString(9, jumlah.getText());


            if (pStatement.executeUpdate()>0)
                JOptionPane.showMessageDialog(this,
                   "Penambahan sukses", "Informasi",
                   JOptionPane.INFORMATION_MESSAGE);
            else
                JOptionPane.showMessageDialog(this,
                   "Penambahan gagal", "Informasi",
                   JOptionPane.INFORMATION_MESSAGE);

            pStatement.close();
            conn.close();

            kode.setText("");
            jenis.setText("");
            kategori.setText("");
            enamjam.setText("");
            duabelasjam.setText("");
            duapuluhempatjam.setText("");
            empatpuluhdelapanjam.setText("");
            overtime.setText("");
            jumlah.setText("");

        }

       catch(ClassNotFoundException e) {
            System.out.println("jdbc.Driver tidak ditemukan");
       }

       catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());

      }
AplikasiRentalKendaraan rental = new AplikasiRentalKendaraan();
rental.setVisible(true);
rental.tampilTabel();
                // TODO add your handling code here:
    }//GEN-LAST:event_simpanActionPerformed

    private void menuutamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuutamaActionPerformed
AplikasiRentalKendaraan tambah2 = new AplikasiRentalKendaraan();
tambah2.setVisible(true);
dispose();
tambah2.tampilTabel();

// TODO add your handling code here:
    }//GEN-LAST:event_menuutamaActionPerformed

    private void showkendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showkendaraanActionPerformed
        // TODO add your handling code here:
        ShowKendaraan show = new ShowKendaraan();
        show.setVisible(true);
    }//GEN-LAST:event_showkendaraanActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahKendaraan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField duabelasjam;
    private javax.swing.JTextField duapuluhempatjam;
    private javax.swing.JTextField empatpuluhdelapanjam;
    private javax.swing.JTextField enamjam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jenis;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField kategori;
    private javax.swing.JTextField kode;
    private javax.swing.JButton menuutama;
    private javax.swing.JTextField overtime;
    private javax.swing.JButton showkendaraan;
    private javax.swing.JButton simpan;
    // End of variables declaration//GEN-END:variables


}
